[package]
name = "{package_name}"
version = "0.1.0"
authors = ["Andrey"]
edition = "2018"

[dependencies]
aoc2020 = \{ path = ".." }
color-eyre = "0.5.8"
structopt = "0.3.20"
thiserror = "1.0.22"
itertools = "0.9.0"
